version: 2

project_name: apprun-dedicated-application-provisioner

before:
  hooks:
    - go mod tidy

builds:
  - id: apprun-dedicated-application-provisioner
    main: ./cmd/apprun-dedicated-application-provisioner
    binary: apprun-dedicated-application-provisioner
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: default
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: 'checksums.txt'

changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - Merge pull request
      - Merge branch

dockers:
  - image_templates:
      - "ghcr.io/tokuhirom/{{ .ProjectName }}:{{ .Version }}-amd64"
    use: buildx
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.source={{ .GitURL }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
    goos: linux
    goarch: amd64

  - image_templates:
      - "ghcr.io/tokuhirom/{{ .ProjectName }}:{{ .Version }}-arm64"
    use: buildx
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.source={{ .GitURL }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
    goos: linux
    goarch: arm64

docker_manifests:
  - name_template: "ghcr.io/tokuhirom/{{ .ProjectName }}:{{ .Version }}"
    image_templates:
      - "ghcr.io/tokuhirom/{{ .ProjectName }}:{{ .Version }}-amd64"
      - "ghcr.io/tokuhirom/{{ .ProjectName }}:{{ .Version }}-arm64"

  - name_template: "ghcr.io/tokuhirom/{{ .ProjectName }}:latest"
    image_templates:
      - "ghcr.io/tokuhirom/{{ .ProjectName }}:{{ .Version }}-amd64"
      - "ghcr.io/tokuhirom/{{ .ProjectName }}:{{ .Version }}-arm64"

release:
  github:
    owner: tokuhirom
    name: apprun-dedicated-application-provisioner
