version: 2

project_name: apprun-dedicated-application-provisioner

before:
  hooks:
    - go mod tidy

builds:
  - id: apprun-dedicated-application-provisioner
    main: ./cmd/apprun-dedicated-application-provisioner
    binary: apprun-dedicated-application-provisioner
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: default
    formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: 'checksums.txt'

changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - Merge pull request
      - Merge branch

dockers_v2:
  - id: apprun-dedicated-application-provisioner
    ids:
      - apprun-dedicated-application-provisioner
    dockerfile: Dockerfile
    images:
      - "ghcr.io/tokuhirom/{{ .ProjectName }}"
    tags:
      - "{{ .Version }}"
      - latest
    platforms:
      - linux/amd64
      - linux/arm64
    labels:
      "org.opencontainers.image.title": "{{ .ProjectName }}"
      "org.opencontainers.image.version": "{{ .Version }}"
      "org.opencontainers.image.source": "{{ .GitURL }}"
      "org.opencontainers.image.revision": "{{ .FullCommit }}"

release:
  github:
    owner: tokuhirom
    name: apprun-dedicated-application-provisioner
