version: 2

project_name: apprun-dedicated-provisioner

before:
  hooks:
    - go mod tidy

builds:
  - id: apprun-dedicated-provisioner
    main: ./cmd/apprun-dedicated-provisioner
    binary: apprun-dedicated-provisioner
    env:
      - CGO_ENABLED=0
      # For reproducible builds
      - SOURCE_DATE_EPOCH=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    # Reproducible builds: use fixed timestamp
    mod_timestamp: "2000-01-01T00:00:00Z"
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X main.version={{.Version}}

archives:
  - id: default
    formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: 'checksums.txt'

changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - Merge pull request
      - Merge branch

dockers_v2:
  - id: apprun-dedicated-provisioner
    ids:
      - apprun-dedicated-provisioner
    dockerfile: Dockerfile
    images:
      - "ghcr.io/tokuhirom/{{ .ProjectName }}"
    tags:
      - "{{ .Version }}"
      - latest
    platforms:
      - linux/amd64
      - linux/arm64
    labels:
      "org.opencontainers.image.title": "{{ .ProjectName }}"
      "org.opencontainers.image.version": "{{ .Version }}"
      "org.opencontainers.image.source": "{{ .GitURL }}"
      "org.opencontainers.image.revision": "{{ .FullCommit }}"

brews:
  - repository:
      owner: tokuhirom
      name: homebrew-tap
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
    name: apprun-dedicated-provisioner
    homepage: "https://github.com/tokuhirom/apprun-dedicated-provisioner"
    description: "CLI tool for managing Sakura Cloud AppRun Dedicated application provisioning"
    license: "MIT"
    test: |
      system "#{bin}/apprun-dedicated-provisioner", "--version"
    install: |
      bin.install "apprun-dedicated-provisioner"

release:
  github:
    owner: tokuhirom
    name: apprun-dedicated-provisioner
